[application]

# `build` & `serve` dist path
platform = "web"

[web.app]
base_path = "penguin-addition"

# HTML title tag content
title = "penguin-addition"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
